version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    command: "npm run start:prod"
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - "5000:3306"
    volumes: 
      - ./.mysql:/docker-entrypoint-initdb.d
    command:
      [mysqld, --character-set-server=utf8, --collation-server=utf8_general_ci]
